services:
  postgres:
    image: postgres:17
    container_name: kvitto-postgres

    environment:
      POSTGRES_DB: kvitto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d kvitto"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build: .
    container_name: kvitto-api

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kvitto
      DB_USER: postgres
      DB_PASSWORD: postgres

      TEST_DB_HOST: postgres
      TEST_DB_PORT: 5432
      TEST_DB_NAME: kvitto_test
      TEST_DB_USER: postgres
      TEST_DB_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

volumes:
  postgres_data: